CREATE DATABASE filesharing OWNER root;

-- GRANT ALL PRIVILEGES ON DATABASE filesharing TO root;
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA filesharing TO root;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA filesharing TO root;